---
- name: restart service nginx
  ansible.builtin.systemd:
    name: nginx
    daemon_reload: true
    enabled: true
    state: restarted
  register: _restart_service_postgres_handler

- name: reload service nginx
  ansible.builtin.systemd:
    name: nginx
    daemon_reload: true
    enabled: true
    state: reloaded
  when: _restart_service_nginx_handler is not defined or _restart_service_nginx_handler is skipped
